### ISSUE TITLE
Problems with mode2 chimeraTE

### ISSUE THREAD

**Issue by Ifengel** [OliveiraDS-hub/ChimeraTE#15] opened 2023-12-19 10:24 UTC
Hello, 

I have problems when running mode 2 of chimeraTEs. 

First of all, I get low levels of alignment of reads against TE fasta, while when I align against genome transcripts I get over 90% alignment. I don't know if this is normal... I add terminal print.

####

```
[Tuesday 12/12/2023 - 16h:23]	Perfoming bowtie2 alignment for TEs...
30940346 reads; of these:
  30940346 (100.00%) were paired; of these:
    29003144 (93.74%) aligned concordantly 0 times
    627643 (2.03%) aligned concordantly exactly 1 time
    1309559 (4.23%) aligned concordantly >1 times
    ----
    29003144 pairs aligned concordantly 0 times; of these:
      46878 (0.16%) aligned discordantly 1 time
    ----
    28956266 pairs aligned 0 times concordantly or discordantly; of these:
      57912532 mates make up the pairs; of these:
        56542099 (97.63%) aligned 0 times
        870064 (1.50%) aligned exactly 1 time
        500369 (0.86%) aligned >1 times
8.63% overall alignment rate
Done!
[Tuesday 12/12/2023 - 16h:52]	Perfoming bowtie2 alignment for transcripts...
30940346 reads; of these:
  30940346 (100.00%) were paired; of these:
    3521991 (11.38%) aligned concordantly 0 times
    4285856 (13.85%) aligned concordantly exactly 1 time
    23132499 (74.76%) aligned concordantly >1 times
    ----
    3521991 pairs aligned concordantly 0 times; of these:
      32350 (0.92%) aligned discordantly 1 time
    ----
    3489641 pairs aligned 0 times concordantly or discordantly; of these:
      6979282 mates make up the pairs; of these:
        5456390 (78.18%) aligned 0 times
        372344 (5.33%) aligned exactly 1 time
        1150548 (16.49%) aligned >1 times
91.18% overall alignment rate
Done!
[Tuesday 12/12/2023 - 17h:13]	Calculating transcripts expression...
Unable to calculate expression due to low rate of alignment! Including all transcripts to the downstream analysis...
Done!
[Tuesday 12/12/2023 - 17h:13]	Identifying chimeric reads...
Done!

```
####

Secondly, my analysis failed in the transcript merge step. chimeraTE correctly creates the chimTEs_raw.tsv but then fails. I don't know what is wrong. I add the error printout. 
```

[Tuesday 12/12/2023 - 17h:21]	Identifying chimeric transcripts with chimeric reads evidence...
[Thursday 14/12/2023 - 04h:00]	Merging coverage from different isoforms...
Traceback (most recent call last):
  File "chimTE_mode2.py", line 188, in <module>
    merging_transc()
  File "scripts/mode2_chim_transcripts.py", line 50, in merging_transc
    chimeras[['isoform','gene']] = chimeras.gene_transc.str.split("_",expand=True)
  File "/home/landeiralab/miniconda3/envs/chimeraTE/lib/python3.6/site-packages/pandas/core/frame.py", line 3041, in __setitem__
    self._setitem_array(key, value)
  File "/home/landeiralab/miniconda3/envs/chimeraTE/lib/python3.6/site-packages/pandas/core/frame.py", line 3067, in _setitem_array
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
```

####

Thank you in advance.

**Comment by OliveiraDS-hub** [comment] 2023-12-20 13:59
Dear @Ifengel

Yes, having a lower proportion of reads aligned against TEs is completely expected. In a scenario where your RNA-seq reads where produced by a polyA tail protocol, most of your reads must come from genes. This is what you are observing, so it's everything normal.

My concern comes before the error. This message is not expected due to your good alignment rates: 

`[Tuesday 12/12/2023 - 17h:13]	Calculating transcripts expression...
Unable to calculate expression due to low rate of alignment! Including all transcripts to the downstream analysis...`

I'm afraid your transcripts.fasta file is not well formatted. Let's check this out.

Please, make these two following commands and send me what you have on your terminal:

`grep '>' transcripts.fasta | head`

`grep '>' transcripts.fasta | sort | uniq -c | awk '$1 > 1' | head`

Change "transcripts.fasta" by the name of your fasta file.

The second command should not print anything.

**Comment by Ifengel** [comment] 2023-12-21 11:34
Dear Daniel, 

This is my terminal after executing the commands:
```
(base) landeiralab@landeiralab-ws:~/ifengel/GRCm38.p6_data/Genoma$ grep '>' gencode.vM22.transcripts_chimeraTE.fa | head
>4933401J01Rik-201_4933401J01Rik
>Gm26206-201_Gm26206
>Xkr4-203_Xkr4
>Xkr4-202_Xkr4
>Xkr4-201_Xkr4
>Gm18956-201_Gm18956
>Gm37180-201_Gm37180
>Gm37363-201_Gm37363
>Gm37686-201_Gm37686
>Gm1992-201_Gm1992
(base) landeiralab@landeiralab-ws:~/ifengel/GRCm38.p6_data/Genoma$ grep '>' gencode.vM22.transcripts_chimeraTE.fa | sort | uniq -c | awk '$1 > 1' | head
(base) landeiralab@landeiralab-ws:~/ifengel/GRCm38.p6_data/Genoma$ 


```

**Comment by OliveiraDS-hub** [comment] 2024-01-28 16:06
Dear @Ifengel , I'm so sorry for the huge delay. 

Indeed your transcripts file is corrected.

Unexpectedly, the message "Unable to calculate expression due to low rate of alignment! Including all transcripts to the downstream analysis" is telling us that the express output wasn't created, which is usually caused by low rate of alignment. Can you confirm me what file you have in any of your replicates folder, within alignment/fpkm_counts/ ?

In these cases, the process continues, because ChimeraTE will then search for chimeras in all genes with at least one read aligned. This will have a time cost, but the process will continue. Can you confirm me that you have the file "genes_expressed_IDs.lst" within the folder "alignment" from any of your replicates?

If the file is there, can you send the result of ``head genes_expressed_IDs.lst`` ?

Still within the alignment folder, can you send me the result of ``head genes.bed``?

It must be something silly with the format of your files. I do need to add checking steps at the beginning of chimeraTE's process. It's coming for the next update.

Thank you for your patience.

**Comment by OliveiraDS-hub** [comment] 2024-03-14 20:02
Dear @Ifengel 

I was unable to reproduce your error with my data. Nevertheless, I have updated ChimeraTE to the version 1.2 with several minor bug fixes, and I encourage you to give it try, perhaps your issue will be solved.

I'm closing this issue, but please don't hesitate to reopen it if you need

Cheers

**Closed by OliveiraDS-hub** 2024-03-14 20:02 UTC
